version: '3.1'

services:
  postgres:
    image: postgres
    ports:
        - 54321:5432
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_DB=plans_dbs

